/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 whale.gltf 
Author: Meleagor (https://sketchfab.com/Meleagor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mythic-whale-stylized-animated-model-124137f938ec4f5390ddde6dffd7c62e
Title: Mythic Whale - Stylized Animated model
*/

import React, { useRef, useMemo, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useGraph } from '@react-three/fiber'
import { SkeletonUtils } from 'three-stdlib'
import Whale from '@/public/whale.gltf'


export default function Model(props) {
  const group = useRef()

  // Load original scene and animations
  const { scene, animations } = useGLTF('/whale.gltf')

  // Clone the scene for safe animation usage
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  // Hook up animations to cloned scene via the group
  const { actions } = useAnimations(animations, group)

  // Play first animation
  useEffect(() => {
    if (actions && animations.length > 0) {
      const action = actions[animations[0].name]
      action?.reset().fadeIn(0.5).play()
    }
  }, [actions, animations])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="045e3ea1e9c64746a04f46524d1bdfd3fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Armature"
                  position={[0, -2.559, 41.458]}
                  rotation={[Math.PI, 0, 0]}
                  scale={30.913}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_71"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <skinnedMesh
                      name="Object_72"
                      geometry={nodes.Object_72.geometry}
                      material={materials.M_Whale}
                      skeleton={nodes.Object_72.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="RetopoFlow"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/whale.gltf')
